version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - aheritier
  - kwhetstone
  - Evildethow
  ignore:
  - dependency-name: org.jenkins-ci.main:jenkins-core
    versions:
    - ">= 0"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
